Fix package import for HTTPRouteFilterExtensionRef (#821)
* Fix package import for HTTPRouteFilterExtensionRef

Caused by merging https://github.com/envoyproxy/gateway/pull/791
without rebasing https://github.com/envoyproxy/gateway/pull/816

Signed-off-by: Arko Dasgupta <arko@tetrate.io>

* fix test

was failing with below error
```
    --- FAIL: TestProcessHTTPRoutes/httproute_with_one_authenticationfilter (0.00s)
        routes_test.go:221:
            	Error Trace:	/Users/arkodebdasgupta/go-workspace/src/github.com/envoyproxy/gateway/internal/provider/kubernetes/routes_test.go:221
            	Error:      	Received unexpected error:
            	            	List on GroupVersionKind gateway.networking.k8s.io/v1beta1, Kind=HTTPRoute specifies selector on field gatewayHTTPRouteIndex, but no index with name gatewayHTTPRouteIndex has been registered for GroupVersionKind gateway.networking.k8s.io/v1beta1, Kind=HTTPRoute
            	Test:       	TestProcessHTTPRoutes/httproute_with_one_authenticationfilter
```

Signed-off-by: Arko Dasgupta <arko@tetrate.io>

Signed-off-by: Arko Dasgupta <arko@tetrate.io>